### ISSUE TITLE
Document process and requirements needed to test workflows

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/WorkflowPlanning#25]
Document the requirements and environment needed to be able to properly test workflows and the process for testing them.

**Comment by mflynn-lanl** [comment]
We're working on creating creating scripts and procedures for testing workflows.

**Comment by ssarrafan** [comment]
Moving to August per @mflynn-lanl

**Comment by ssarrafan** [comment]
@hubin-keio @mflynn-lanl any updates on this issue?  Will you be able to close it by the end of the week?

**Comment by hubin-keio** [comment]
The ticket has been reassigned to Michal. We'll have an internal meeting on Monday to go over the requirements of the document.

**Comment by ssarrafan** [comment]
> The ticket has been reassigned to Michal. We'll have an internal meeting on Monday to go over the requirements of the document.

Thanks for the update @hubin-keio.  I'll go ahead and move this to September sprint as it seems like it's being worked on. If that's not the case let me know and I will remove from the sprint.

**Comment by Michal-Babins** [comment]
Workflow testing documentation here:

https://github.com/microbiomedata/workflow_testing

**Comment by ssarrafan** [comment]
> Workflow testing documentation here:
> 
> https://github.com/microbiomedata/workflow_testing

Thank you @Michal-Babins.  Can we consider this issue closed?

**Comment by Michal-Babins** [comment]
@ssarrafan Yes, I can go ahead and close the issue.
