### ISSUE TITLE
Process EMP500 data in preparation for release to portal

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/WorkflowPlanning#28]
Part of the goal of getting more data process for the portal

@hubin-keio please let me know if it should be in a different repo

**Comment by ssarrafan** [comment]
Moving to December sprint per Slack message from @hubin-keio

**Comment by ssarrafan** [comment]
Per Slack moving this to March per @hubin-keio

**Comment by Michal-Babins** [comment]
EMP 500 Soil SE data may not be included in the release. There are a few issues that are causing the SE workflow to fail that is attributed to data quality. The main issues that appear with this data are:

1. Some files to begin with have too little reads to instantiate any processes 
2. After quality filtering, there is either not enough reads to be assembled or only a few contigs remain after assembly 
3. Gottcha2 is unable to classify any taxa from few reads and how the workflow is set up, this causes failure and does not allow for the workflow to continue

Data stats can be found here:
[https://docs.google.com/document/d/1VH6qVmsetx5wRhf5dVZM53ZFEQ1DZidLjNP6gd0bGLA/edit](https://docs.google.com/document/d/1VH6qVmsetx5wRhf5dVZM53ZFEQ1DZidLjNP6gd0bGLA/edit)

There may be a need to implement filtering for data that we choose to process that is grabbed from external data repositories before we begin the data processing execution. For now we can proceed with PE emp 500 soil data.

**Comment by hubin-keio** [comment]
Will do the ingestion of the PE data once we receive the GOLD ID (expected in the first week of April).

**Comment by ssarrafan** [comment]
Moving to April per @hubin-keio

**Comment by ssarrafan** [comment]
@hubin-keio I'll close this issue now that the data has been released on the portal.  Let me know if I can help create new issues for May to work on the rest of the EMP data.
