### ISSUE TITLE
Process Bioscales data in preparation for release to portal

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/WorkflowPlanning#29]
Part of the goal of getting more data process for the portal

@hubin-keio please let me know if it should be in a different repo

**Comment by ssarrafan** [comment]
Moving to December sprint per Slack message from @hubin-keio

**Comment by ssarrafan** [comment]
@hubin-keio let me know if this should be re-assigned or taken out of the March sprint

**Comment by ssarrafan** [comment]
Moving to April per @hubin-keio

**Comment by Michal-Babins** [comment]
Ingest of this data already happened, confirmed with Shane. Will close this ticket.
