### ISSUE TITLE
Post 2022 GSP Cleanup

### ISSUE THREAD

**Issue by scanon** [microbiomedata/WorkflowPlanning#30]
List of data sets that failed and still need work.

* PMI: 46fa6094-72ca-4409-9457-4403e3b90ab4  nmdc_metag     Failed     gold:Gp0116341  1.0.6      metag_annotation nmdc:mga0yg80  nmdc:sys0d7hh20 2021-12-15T01:53:24.853Z
* SPRUCE: 344b898a-c0b3-4f85-bb35-01a3d3117d35  nmdc_metag     Failed     gold:Gp0138728  1.0.6      metag_annotation nmdc:mga0k311  nmdc:sys0xj7x26 2021-12-18T01:21:48.441Z

**Comment by aclum** [comment]
Annotation will be redone after re-iding, closing this ticket.
