### ISSUE TITLE
MetaG update from JGI

### ISSUE THREAD

**Issue by hubin-keio** [microbiomedata/WorkflowPlanning#32]
JGI is updating the metaG workflow output structure and we need to update the NMDC metaG correspondingly so that the metaG workflows from these two sources stay in sync.

**Comment by ssarrafan** [comment]
@scanon and @hubin-keio what is the status of this issue?  Are you actively working on it In April?  Should it be moved out of this sprint?

**Comment by ssarrafan** [comment]
@hubin-keio and @scanon do you have any updates on this issue?  I am trying to close out the sprint on time since I'll be off next week.  Thanks for your help.

**Comment by hubin-keio** [comment]
We are working on this. Amy just created a doc to explain the structure and packaging. We'll need to go through it and address anything that may be different from the NMDC side. Please move this issue to the May Sprint. Thanks.

**Comment by ssarrafan** [comment]
@scanon  moving this to the backlog. Let me know if it should be assigned to someone else. 
FYI @hubin-keio @emileyfadrosh

**Comment by ssarrafan** [comment]
@hubin-keio @scanon isn't this done?  I'm closing this issue but let me know if we are still waiting on something.
Backlog cleanup 12-2023
