### ISSUE TITLE
Add mongoDB and validation to automation workflow

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/WorkflowPlanning#37]
Add details or list of tasks here

**Comment by ssarrafan** [comment]
Moving to July sprint per @Michal-Babins

**Comment by Michal-Babins** [comment]
Still in progress. Work plan will be hashed out between workflow and runtime team.

**Comment by ssarrafan** [comment]
> Still in progress. Work plan will be hashed out between workflow and runtime team.

I will move to August. If at the meeting you decide this isn't a priority for August please let me know so I can remove from the August board and add the backlog label.  Thanks!

**Comment by ssarrafan** [comment]
@Michal-Babins are you actively working on this for the next two weeks?

**Comment by ssarrafan** [comment]
Moving this to the backlog. @Michal-Babins @hubin-keio let me know if this is part of the werkflow squad work this month?

**Comment by ssarrafan** [comment]
Closing per @aclum
