### ISSUE TITLE
monitor the health status for NMDC EDGE

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/WorkflowPlanning#38]
Bin requested this GH issue for Mark.  Let me know if it should be in a different repo.

**Comment by ssarrafan** [comment]
@hubin-keio @mflynn-lanl any update on this issue?  Are you blocked on anything?  
It's mid-sprint so checking on issues that are still under to-do.

**Comment by hubin-keio** [comment]
@mflynn-lanl, can you update it? I know you have been working on Prometheus,

**Comment by mflynn-lanl** [comment]
Yes, I am still working on this. I created a test NMDC EDGE site with an endpoint for Prometheus and can monitor basic VM health metrics.

**Comment by ssarrafan** [comment]
@mflynn-lanl @hubin-keio I assume that the monitoring is set up and will close this issue. If there are next steps or additional work on this please let me know and we can create issues for the August sprint.
